
service: sls-cicd

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  timeout: 3

functions:
  logger:
    handler: handler.logger
    events:
      - http:
          path: message
          method: get
